version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
        - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: maria_root_pass
    volumes:
      - "./mariadb-data/data:/var/lib/mysql/data"
      - "./mariadb-data/logs:/var/lib/mysql/logs"
